# Welcome to Jekyll!
# Site settings

title: The Dragon's Reach | Tracking China's Belt and Road Initiative
description: > # this means to ignore newlines
  China is investing more than $1 trillion in roads, bridges, railways, ports, and power plants in other countries — a bold strategy to steer global commerce its way. In this project, <a href="https://www.bbg.gov/">BBG</a> news agencies examine how the 'Belt and Road Initiative' is transforming lives, reshaping landscapes and tilting the geopolitical balance.
title_short: The Dragon's Reach
description_short: >
  China is investing more than $1 trillion in roads, bridges, railways, ports, and power plants in other countries — a bold strategy to steer global commerce its way.
description_footer: > 
  This project explores China's growing investments around the world. It’s a joint initiative by Radio Free Europe/Radio Liberty, Middle East Broadcasting Networks, Voice of America, Radio Free Asia and the Office of Cuba Broadcasting. They’re overseen by the Broadcasting Board of Governors.


# SET URL_BASE == "" FOR LOCAL DEVELOPMENT, OTHERWISE USE THE PATH WHERE IT'LL BE HOSTED.
canonical_url_base: ""
# canonical_url_base: "http://silkroadregained"

baseurl: "" # the subpath of your site, e.g. /blog



# ADD A WARNING FLAG 
development_mode: false
development_warning: This site is currently under active development.



categories_list:
  - name: voa
    namePretty: VOA
    nameSheet: VOA
    nameFull: Voice of America
    logo: http://internetfreedom.io/img/logo__voa.png
    url: https://www.voanews.com
    urlPretty: voanews.com
    description: >
      Voice of America provides trusted and objective news and information in 45 languages to a measured weekly audience of more than 236.8 million people around the world.  For over 75 years, VOA journalists have told American stories and supplied content that many people cannot get locally: objective news and information about the US, their specific region and the world.
  - name: rferl
    namePretty: RFE/RL
    nameSheet: RFERL
    nameFull: Radio Free Europe / Radio Liberty
    logo: http://internetfreedom.io/img/logo__rferl.png
    url: https://www.rferl.org
    urlPretty: rferl.org
    description: >
      RFE/RL’s mission is to promote democratic values and institutions by reporting the news in countries where a free press is banned by the government or not fully established. Our journalists provide what many people cannot get locally: uncensored news, responsible discussion, and open debate.
  - name: rfa
    namePretty: RFA
    nameSheet: RFA
    nameFull: Radio Free Asia
    logo: http://internetfreedom.io/img/logo__rfa.png
    url: https://www.rfa.org
    urlPretty: rfa.org
    description: Radio Free Asia brings award-winning, domestic journalism and uncensored content to people in six Asian countries that restrict free speech, freedom of the press, and access to reliable information beyond their borders. RFA also provides educational and cultural programming, as well as forums for audiences to engage in open dialogue and freely express opinions.
  - name: alhurra
    namePretty: Alhurra
    nameSheet: Alhurra
    nameFull: Alhurra
    logo: http://internetfreedom.io/img/logo__mbn.png
    url: https://www.alhurra.com
    urlPretty: alhurra.com
    description: Middle East Broadcasting Networks is the non-profit news organization that operates Alhurra Television, Radio Sawa and MBN Digital reaching audiences in 22 countries across the Middle East and North Africa.
  - name: martí
    namePretty: Martí
    nameSheet: Martí
    nameFull: Martí Noticias
    logo: https://placehold.it/90x90
    url: https://www.martinoticias.com
    urlPretty: martinoticias.com
    description: >
      The Office of Cuba Broadcasting’s mission is to promote freedom and democracy by providing the people of Cuba with objective news and information programming.






# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - ai2html
  - sidebar-app
  - README.md
  - TECHNICAL.md
#- animation
sass:
  style: compressed

#permalink: /:categories/:title:output_ext
permalink: /:categories/:title
